### ISSUE TITLE
Adding API cURLs/Swagger

### ISSUE THREAD

**Issue by ajayjha5899** [ajaynegi45/Library-API#6]
For the sake of convenience of API testing & maintainence, we can do the following: 
1. Add cURLs for all the APIs to the README of this project
2. Add Swagger integration for auto documentation. 

I would be happy to do any (or both) if you agree.

**Comment by ajaynegi45** [comment]
Hi @ajayjha5899,

Thank you for expressing your interest in working on the issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.

**Comment by ajayjha5899** [comment]
@ajaynegi45 are we proceeding with '1' or '2'?

**Comment by ajayjha5899** [comment]
Swagger is added in this PR - #7 

I believe this should be sufficient.
